[[chains]]
  name = "OP Mainnet"
  identifier = "mainnet/op"
  chain_id = 10
  rpc = ["https://mainnet.optimism.io"]
  explorers = ["https://explorer.optimism.io"]
  superchain_level = 2
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "Base"
  identifier = "mainnet/base"
  chain_id = 8453
  rpc = ["https://mainnet.base.org"]
  explorers = ["https://explorer.base.org"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "Lyra Chain"
  identifier = "mainnet/lyra"
  chain_id = 957
  rpc = ["https://rpc.lyra.finance"]
  explorers = ["https://explorer.lyra.finance"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "Metal L2"
  identifier = "mainnet/metal"
  chain_id = 1750
  rpc = ["https://rpc.metall2.com"]
  explorers = ["https://explorer.metall2.com"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "Mode"
  identifier = "mainnet/mode"
  chain_id = 34443
  rpc = ["https://mainnet.mode.network"]
  explorers = ["https://explorer.mode.network"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "Orderly Mainnet"
  identifier = "mainnet/orderly"
  chain_id = 291
  rpc = ["https://rpc.orderly.network"]
  explorers = ["https://explorer.orderly.network"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "PGN (Public Goods Network)"
  identifier = "mainnet/pgn"
  chain_id = 424
  rpc = ["https://rpc.publicgoods.network"]
  explorers = ["https://explorer.publicgoods.network"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "RACE Mainnet"
  identifier = "mainnet/race"
  chain_id = 6805
  rpc = ["https://racemainnet.io"]
  explorers = ["https://racescan.io/"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "SuperLumio"
  identifier = "mainnet/superlumio"
  chain_id = 8866
  rpc = ["https://mainnet.lumio.io"]
  explorers = ["https://explorer.lumio.io"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "Zora"
  identifier = "mainnet/zora"
  chain_id = 7777777
  rpc = ["https://rpc.zora.energy"]
  explorers = ["https://explorer.zora.energy"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "mainnet"

[[chains]]
  name = "OP Sepolia Testnet"
  identifier = "sepolia/op"
  chain_id = 11155420
  rpc = ["https://sepolia.optimism.io"]
  explorers = ["https://sepolia-optimistic.etherscan.io"]
  superchain_level = 2
  [chains.parent]
    type = "L2"
    chain = "sepolia"

[[chains]]
  name = "Base Sepolia Testnet"
  identifier = "sepolia/base"
  chain_id = 84532
  rpc = ["https://sepolia.base.org"]
  explorers = ["https://sepolia-explorer.base.org"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "sepolia"

[[chains]]
  name = "Metal L2 Testnet"
  identifier = "sepolia/metal"
  chain_id = 1740
  rpc = ["https://testnet.rpc.metall2.com"]
  explorers = ["https://testnet.explorer.metall2.com"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "sepolia"

[[chains]]
  name = "Mode Testnet"
  identifier = "sepolia/mode"
  chain_id = 919
  rpc = ["https://sepolia.mode.network"]
  explorers = ["https://sepolia.explorer.mode.network"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "sepolia"

[[chains]]
  name = "Sepolia PGN (Public Goods Network)"
  identifier = "sepolia/pgn"
  chain_id = 58008
  rpc = ["https://sepolia.publicgoods.network"]
  explorers = ["https://explorer.sepolia.publicgoods.network"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "sepolia"

[[chains]]
  name = "Zora Sepolia Testnet"
  identifier = "sepolia/zora"
  chain_id = 999999999
  rpc = ["https://sepolia.rpc.zora.energy"]
  explorers = ["https://sepolia.explorer.zora.energy"]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "sepolia"

[[chains]]
  name = "Base devnet 0"
  identifier = "sepolia-dev-0/base-devnet-0"
  chain_id = 11763072
  rpc = [""]
  explorers = [""]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "sepolia-dev-0"

[[chains]]
  name = "OP Labs Sepolia devnet 0"
  identifier = "sepolia-dev-0/oplabs-devnet-0"
  chain_id = 11155421
  rpc = [""]
  explorers = [""]
  superchain_level = 1
  [chains.parent]
    type = "L2"
    chain = "sepolia-dev-0"
