name: Goerli
l1:
  chain_id: 5
  public_rpc: https://goerli.gateway.tenderly.co
  explorer: https://goerli.etherscan.io

protocol_versions_addr: "0x0C24F5098774aA366827D667494e9F889f7cFc08"

regolith_time: 0         # Thu  1 Jan 1970 00:00:00 UTC genesis, overriden by individual chains
canyon_time: 1699981200  # Tue 14 Nov 2023 17:00:00 UTC
delta_time: 1703116800   # Thu 21 Dec 2023 00:00:00 UTC
ecotone_time: 1707238800 # Tue  6 Feb 2024 17:00:00 UTC
