name = "rehearsal-0-bn"
protocol_versions_addr = "0x72B9c5a159B0dEE8331a268791aa432619693c06"
superchain_config_addr = "0x672F11f34b7bE67C13A6FCba819c339bc3B0a585"
op_contracts_manager_addr = "0x0fcD165e2531C934a186e3a412D58Daa241E0Ad0"

[hardforks]

[l1]
  chain_id = 11155111
  public_rpc = "https://ci-sepolia-l1.optimism.io"
  explorer = ""
