name = "Camp Network Testnet V2"
public_rpc = "https://rpc.camp-network-testnet.gelato.digital"
sequencer_rpc = "https://rpc.camp-network-testnet.gelato.digital"
explorer = "https://camp-network-testnet.blockscout.com"
superchain_level = 0
governed_by_optimism = false
data_availability_type = "eth-da"
chain_id = 325000
batch_inbox_addr = "0xFF00000000000000000000000000000000325000"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600
superchain = "sepolia"
base_fee_vault_recipient = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
l1_fee_vault_recipient = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
sequencer_fee_vault_recipient = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
deployment_tx_hash = "0x124b0011271c5810826f74bf8767467009e136fecf0f8e80327b0000fb0456e5"
deployment_l1_contracts_version = "tag://op-contracts/v1.8.0-rc.4"
deployment_l2_contracts_version = "tag://op-contracts/v1.7.0-beta.1+l2-contracts"

[hardforks]
  canyon_time = 0
  delta_time = 0
  ecotone_time = 0
  fjord_time = 0
  granite_time = 1723478400
  holocene_time = 1732633200

[optimism]
  eip1559_elasticity = 10
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1718120160
  [genesis.l1]
    hash = "0x124b0011271c5810826f74bf8767467009e136fecf0f8e80327b0000fb0456e5"
    number = 6086446
  [genesis.l2]
    hash = "0x7c7c4f48d2f33a04c5cbabc8b6ba6315f283d6ae0a874118ceb8881e21bfd05e"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x624811105f39936d5ce277d93292061abfedd4d5"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000f4240"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
  ProxyAdminOwner = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
  Guardian = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
  Challenger = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
  Proposer = "0x2bECfba7B2BE6182e9BD2eF10E83414e22fAB673"
  UnsafeBlockSigner = "0x8dEa38366Bc426C6822AebE51210212542544C77"
  BatchSubmitter = "0x624811105f39936D5cE277d93292061ABfEDD4D5"

  [addresses]
  SystemConfigOwner = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
  ProxyAdminOwner = "0x6DCd6421558F1478251231798fe7500fB23a1E84"
  Guardian = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
  Challenger = "0xDA477C3d6faD3C0fCE508a6cF791967D7cf14aFb"
  Proposer = "0x2bECfba7B2BE6182e9BD2eF10E83414e22fAB673"
  UnsafeBlockSigner = "0x8dEa38366Bc426C6822AebE51210212542544C77"
  BatchSubmitter = "0x624811105f39936D5cE277d93292061ABfEDD4D5"
  AddressManager = "0x2677986E7f92cBBfC0D96C23a2e2897E9d7F240f"
  L1CrossDomainMessengerProxy = "0x3f4A9443DdC60a0d0Dcea92C627849045B5A840f"
  L1ERC721BridgeProxy = "0x1239F374612F4674305ba7c60332b16e5396e125"
  L1StandardBridgeProxy = "0x5c3Ec2182Be9FbeA0da50d517362a069e13FB50E"
  L2OutputOracleProxy = "0x6AD70b6C30Aa872FcbB86958A6aB950b3125a6f0"
  OptimismMintableERC20FactoryProxy = "0xb6036E2330FE7aeDeCbdeE5CD773704dE92CcA37"
  OptimismPortalProxy = "0x4238fAb3746D41e18c87138b505B6857CeF6cd1F"
  SystemConfigProxy = "0x7aA405B004401Be20d4A587de34aEeC99bE0b268"
  ProxyAdmin = "0x488fF7476709920e49293C4d695D3A0256AB6EAB"
  SuperchainConfig = "0xa9f8C27487B1D56370437d2c629FAC8cA7d74958"
  AnchorStateRegistryProxy = "0x16E79A16BDCC2Aee043E88bBf5A2624f78e9Fc64"
  DelayedWETHProxy = "0xcea954f7bb597F1Fa2bFe3f88507f9c34fee3148"
  DisputeGameFactoryProxy = "0x83BaE25FDa209b31E903D3DD932906E2718A6E89"
  MIPS = "0x827d2263d0Ba85EdE37e8a60559eebe50d72aC7C"
  PreimageOracle = "0xf0aAc9852f36DB4a7a4e033d94887b73C849D6A5"
