["op-contracts/v1.4.0"] # Fault Proofs https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.4.0
address_manager = ""
l1_cross_domain_messenger = "0xc919b535f7bbbaa57f32b602f26000e3997c22c933efbb92a36e053b20b2b4b1" # version 2.3.0
l1_erc721_bridge = "0xa1a3ea3996797cf5035dafff9335386f8b00c58ff22aaa4c34b02c4ae7cf5e8a" # version 2.1.0
l1_standard_bridge = "0x6894839591ba2aa1f6ba43526113e25fd795ec5c5a48202e664c931cd170aaee" # version 2.1.0
optimism_mintable_erc20_factory = "0xb8ec72533005496795f8fc0c71f0312578ff626f7b94699984e1add6dc2f3b88" # version 1.9.0
optimism_portal = "0x2b0610230634fccf9d05f4aaefceffef9e04aa99910798d42823e0068eb07eca" # version 3.10.0
system_config = "0x1245886f18eada47816eba66ec353eb9a5dad795a5e36df78067f66657018e32" # version 2.2.0
protocol_versions = "" # version 1.0.0
anchor_state_registry = "0x07a466697584157d8926768fd99d30499dddc52aec7e2e620f430f3498b26dee" # version 1.0.0
delayed_weth = "0x430b15595a625dc821f34b42c354676de32c2f112fbd89978b8196cf66d823d5" # version 1.0.0
dispute_game_factory = "0x0d25ffc72ede825443defd6dfb435f5ddeb2e9ce0e3da3e40af069f3ba6bef0f" # version 1.0.0
fault_dispute_game = "0x855bb3581555d472e91a3fedae1a0bf141105a555aff2b49af28bf30394b6bc1" # version 1.2.0
permissioned_dispute_game = "0xea3ed5f9eef95def7ff4b849f0765a7884268a0c7809dfff6a02214390c23ada" # version 1.2.0
