latest_stable = "1.4.0"
latest_rc = "1.5.0-rc.4"

[[prestates."1.5.0-rc.4"]]
type = "cannon32"
hash = "0x0354eee87a1775d96afee8977ef6d5d6bd3612b256170952a01bf1051610ee01"

[[prestates."1.5.0-rc.4"]]
type = "cannon64"
hash = "0x03ee2917da962ec266b091f4b62121dc9682bb0db534633707325339f99ee405"

[[prestates."1.5.0-rc.3"]]
type = "cannon32"
hash = "0x039facea52b20c605c05efb0a33560a92de7074218998f75bcdf61e8989cb5d9"

[[prestates."1.5.0-rc.3"]]
type = "cannon64"
hash = "0x039970872142f48b189d18dcbc03a3737338d098b0101713dc2d6710f9deb5ef"

[[prestates."1.5.0-rc.2"]]
type = "cannon32"
hash = "0x035ac388b5cb22acf52a2063cfde108d09b1888655d21f02f595f9c3ea6cbdcd"

[[prestates."1.5.0-rc.2"]]
type = "cannon64"
hash = "0x03a7d967025dc434a9ca65154acdb88a7b658147b9b049f0b2f5ecfb9179b0fe"

[[prestates."1.5.0-rc.1"]]
type = "cannon32"
hash = "0x03dfa3b3ac66e8fae9f338824237ebacff616df928cf7dada0e14be2531bc1f4"

[[prestates."1.5.0-rc.1"]]
type = "cannon64"
hash = "0x03f83792f653160f3274b0888e998077a27e1f74cb35bcb20d86021e769340aa"

[[prestates."1.4.1-rc.3"]]
type = "cannon64"
hash = "0x03d7f817d7bb1321533aeeee5e0f2031cc69d167c4a17bf2816b4cc8b1be4077"

[[prestates."1.4.1-rc.3"]]
type = "cannon32"
hash = "0x03ea123151750b03569369130a73c390b0b5e10c722ab42d762d116318325bb7"

[[prestates."1.4.1-rc.2"]]
type = "cannon64"
hash = "0x0386cde2f2b1bde1189ac9c9b7d66774e6260eca778223def326bfe680c14ab9"

[[prestates."1.4.1-rc.2"]]
type = "cannon32"
hash = "0x03045fd433fb5391c40751939d7cb5e9dfe83cf156f9395566a311e7fe9d3aa2"

[[prestates."1.4.1-rc.1"]]
type = "cannon64"
hash = "0x0386cde2f2b1bde1189ac9c9b7d66774e6260eca778223def326bfe680c14ab9"

[[prestates."1.4.1-rc.1"]]
type = "cannon32"
hash = "0x03045fd433fb5391c40751939d7cb5e9dfe83cf156f9395566a311e7fe9d3aa2"

[[prestates."1.4.0"]]
type = "cannon64"
hash = "0x03b7eaa4e3cbce90381921a4b48008f4769871d64f93d113fcadca08ecee503b"

[[prestates."1.4.0"]]
type = "cannon32"
hash = "0x03f89406817db1ed7fd8b31e13300444652cdb0b9c509a674de43483b2f83568"

[[prestates."1.4.0-unichain-mainnet"]]
type = "cannon64"
hash = "0x03d5baff435a6828cfa13679e7ef34ac73d4d674550426c7d9a8005deb6a6db3"

[[prestates."1.4.0-unichain-mainnet"]]
type = "cannon32"
hash = "0x0336751a224445089ba5456c8028376a0faf2bafa81d35f43fab8730258cdf37"

[[prestates."1.4.0-rc.3"]]
type = "cannon64"
hash = "0x03b7eaa4e3cbce90381921a4b48008f4769871d64f93d113fcadca08ecee503b"

[[prestates."1.4.0-rc.3"]]
type = "cannon32"
hash = "0x03f89406817db1ed7fd8b31e13300444652cdb0b9c509a674de43483b2f83568"

[[prestates."1.4.0-rc.2"]]
type = "cannon64"
hash = "0x0348ce2059f718af75729c2c56860551b46b665956a641b3cb2cd51e50b7b725"

[[prestates."1.4.0-rc.2"]]
type = "cannon32"
hash = "0x0364e4e72922e7d649338f558f8a14b50ca31922a1484e73ea03987fb1516095"

[[prestates."1.4.0-rc.1"]]
type = "cannon64"
hash = "0x032e5d6119ee983cb87deae3eef16ea6086f2347433c99f1820d60f36a24a6e6"

[[prestates."1.4.0-rc.1"]]
type = "cannon32"
hash = "0x03925193e3e89f87835bbdf3a813f60b2aa818a36bbe71cd5d8fd7e79f5e8afe"

[[prestates."1.3.1-ink"]]
type = "cannon32"
hash = "0x03c50b9fd04bdadc228205f340767bbf2d01a030aec39903120d3559d94bb8cc"

[[prestates."1.3.1"]]
type = "cannon32"
hash = "0x038512e02c4c3f7bdaec27d00edf55b7155e0905301e1a88083e4e0a6764d54c"

[[prestates."1.3.1-rc.2"]]
type = "cannon32"
hash = "0x038512e02c4c3f7bdaec27d00edf55b7155e0905301e1a88083e4e0a6764d54c"

[[prestates."1.3.1-rc.1"]]
type = "cannon32"
hash = "0x03e806a2859a875267a563462a06d4d1d1b455a9efee959a46e21e54b6caf69a"

[[prestates."1.3.0-rc.3"]]
type = "cannon32"
hash = "0x030de10d9da911a2b180ecfae2aeaba8758961fc28262ce989458c6f9a547922"

[[prestates."1.3.0-rc.2"]]
type = "cannon32"
hash = "0x0385c3f8ee78491001d92b90b07d0cf387b7b52ab9b83b4d87c994e92cf823ba"

[[prestates."1.3.0-rc.1"]]
type = "cannon32"
hash = "0x0367c4aa897bffbded0b523f277ca892298dc3c691baf37bc2099b86024f9673"

[[prestates."1.2.0"]]
type = "cannon32"
hash = "0x03617abec0b255dc7fc7a0513a2c2220140a1dcd7a1c8eca567659bd67e05cea"

[[prestates."1.1.0"]]
type = "cannon32"
hash = "0x03e69d3de5155f4a80da99dd534561cbddd4f9dd56c9ecc704d6886625711d2b"

[[prestates."1.0.1"]]
type = "cannon32"
hash = "0x0398bdd93e2e9313befdf82beb709da6a4daf35ce1abb42d8a998ec9bc1c572e"

[[prestates."1.0.0"]]
type = "cannon32"
hash = "0x037ef3c1a487960b0e633d3e513df020c43432769f41a634d18a9595cbf53c55"

[[prestates."0.3.1"]]
type = "cannon32"
hash = "0x037ef3c1a487960b0e633d3e513df020c43432769f41a634d18a9595cbf53c55"

[[prestates."0.3.0"]]
type = "cannon32"
hash = "0x034c8cc69f22c35ae386a97136715dd48aaf97fd190942a111bfa680c2f2f421"

[[prestates."0.2.0"]]
type = "cannon32"
hash = "0x031e3b504740d0b1264e8cf72b6dde0d497184cfb3f98e451c6be8b33bd3f808"

[[prestates."0.1.0"]]
type = "cannon32"
hash = "0x038942ec840131a63c49fa514a3f0577ae401fd5584d56ad50cdf5a8b41d4538"

[[prestates."0.0.1"]]
type = "cannon32"
hash = "0x03babef4b4c6d866d56e6356d961839fd9475931d11e0ea507420a87b0cadbdd"
