name = "Base Sepolia Testnet"
chain_id = 84532
public_rpc = "https://sepolia.base.org"
sequencer_rpc = "https://sepolia-sequencer.base.org"
explorer = "https://sepolia-explorer.base.org"
superchain_level = 1
standard_chain_candidate = true # This is a temporary field which causes most of the standard validation checks to run on this chain
superchain_time = 0 # Missing hardfork times are inherited from superchain.yaml
batch_inbox_addr = "0xfF00000000000000000000000000000000084532"
canyon_time = 1699981200 # Tue 14 Nov 2023 17:00:00 UTC
delta_time = 1703203200 # Fri 22 Dec 2023 00:00:00 UTC
ecotone_time = 1708534800 # Wed 21 Feb 2024 17:00:00 UTC
fjord_time = 1716998400 # Wed 29 May 2024 16:00:00 UTC
block_time = 2
seq_window_size = 3600

[genesis]
  l2_time = 1695768288
  [genesis.l1]
    hash = "0xcac9a83291d4dec146d6f7f69ab2304f23f5be87b1789119a0c5b1e4482444ed"
    number = 4370868
  [genesis.l2]
    hash = "0x0dcc9e089e30b90ddfc55be9a37dd15bc551aeee999d2e2b51414c54eaf934e4"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x6CDEbe940BC0F26850285cacA097C11c33103E47"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000834"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000f4240"
    gasLimit = 25000000

[addresses]
  AddressManager = "0x709c2B8ef4A9feFc629A8a2C1AF424Dc5BD6ad1B"
  BatchSubmitter = "0x6CDEbe940BC0F26850285cacA097C11c33103E47"
  Challenger = "0xDa3037Ff70Ac92CD867c683BD807e5A484857405"
  Guardian = "0x7a50f00e8D05b95F98fE38d8BeE366a7324dCf7E"
  L1CrossDomainMessengerProxy = "0xC34855F4De64F1840e5686e64278da901e261f20"
  L1ERC721BridgeProxy = "0x21eFD066e581FA55Ef105170Cc04d74386a09190"
  L1StandardBridgeProxy = "0xfd0Bf71F60660E2f608ed56e1659C450eB113120"
  L2OutputOracleProxy = "0x84457ca9D0163FbC4bbfe4Dfbb20ba46e48DF254"
  OptimismMintableERC20FactoryProxy = "0xb1efB9650aD6d0CC1ed3Ac4a0B7f1D5732696D37"
  OptimismPortalProxy = "0x49f53e41452C74589E85cA1677426Ba426459e85"
  Proposer = "0x20044a0d104E9e788A0C984A2B7eAe615afD046b"
  ProxyAdmin = "0x0389E59Aa0a41E4A413Ae70f0008e76CAA34b1F3"
  ProxyAdminOwner = "0x0fe884546476dDd290eC46318785046ef68a0BA9"
  SystemConfigOwner = "0x0fe884546476dDd290eC46318785046ef68a0BA9"
  SystemConfigProxy = "0xf272670eb55e895584501d564AfEB048bEd26194"
  UnsafeBlockSigner = "0xb830b99c95Ea32300039624Cb567d324D4b1D83C"
