name = "Boba Sepolia Testnet"
public_rpc = "https://sepolia.boba.network"
sequencer_rpc = "https://sepolia.boba.network"
explorer = "https://testnet.bobascan.com"
superchain_level = 0
governed_by_optimism = false
data_availability_type = "eth-da"
chain_id = 28882
batch_inbox_addr = "0xfFf0000000000000000000000000000000028882"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  regolith_time = 1705600788 # Thu 18 Jan 2024 17:59:48 UTC
  canyon_time = 1705600788 # Thu 18 Jan 2024 17:59:48 UTC
  delta_time = 1709078400 # Wed 28 Feb 2024 00:00:00 UTC
  ecotone_time = 1709078400 # Wed 28 Feb 2024 00:00:00 UTC
  fjord_time = 1722297600 # Tue 30 Jul 2024 00:00:00 UTC
  granite_time = 1726470000 # Mon 16 Sep 2024 07:00:00 UTC
  holocene_time = 1736150400 # Mon Jan 6 08:00:00 UTC
  pectra_blob_schedule_time = 1743534000 # Tue Apr 01 2025 19:00:00 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1705600788
  [genesis.l1]
    hash = "0x632d8caedbfd573e09c1b49134bd5147147e0904e0f04eba15c662be0258f517"
    number = 5109513
  [genesis.l2]
    hash = "0x097654c4c932c97808933b42179388f7bbcefaed3bd93fdf69157e19f1deea0e"
    number = 511
  [genesis.system_config]
    batcherAddress = "0xf598b6388eC06945021699F0bbb23dfCFc5edbE8"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000834"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000f4240"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x17070B4AF21625106E7971983Aa524f59EA40c57"
  ProxyAdminOwner = "0x17070B4AF21625106E7971983Aa524f59EA40c57"
  Guardian = "0x66930dd34EA64bD4B9F32464e363511b49966C5D"
  Challenger = "0x17070B4AF21625106E7971983Aa524f59EA40c57"
  Proposer = "0x0AB197DdeE146c01A0C6Cadf3d91fbb4340A999A"
  UnsafeBlockSigner = "0x274a47436C7C896827633805d924d41BBa1D19e9"
  BatchSubmitter = "0xf598b6388eC06945021699F0bbb23dfCFc5edbE8"

[addresses]
  AddressManager = "0xC62C429390B7bCE9960fa647d5556CA7238168AB"
  L1CrossDomainMessengerProxy = "0x9253E76E2fA3f72aF18e08914b3528F725779495"
  L1ERC721BridgeProxy = "0x13B397A08322973B45e063F29746Fb278f189916"
  L1StandardBridgeProxy = "0x244d7b81EE3949788Da5F1178D911e83bA24E157"
  L2OutputOracleProxy = "0xdBdb238185f9BB40f742aE249f9a083381EC39eC"
  OptimismMintableERC20FactoryProxy = "0xE6ebece6936528804BB4c43AdcA10c2623919852"
  OptimismPortalProxy = "0xB079E6FA9B3eb072fEbf7F746044834eab308dB6"
  SystemConfigProxy = "0xfDC9bCE032cEF55a71b4fde9B9a2198ad1551965"
  ProxyAdmin = "0x66930dd34EA64bD4B9F32464e363511b49966C5D"
  SuperchainConfig = "0x029A23c6E9D3026f984cd1Fd9C47906e4F5327F3"
