name = "Ink Sepolia"
chain_id = 763373
public_rpc = "https://rpc-gel-sepolia.inkonchain.com"
sequencer_rpc = "https://rpc-gel-sepolia.inkonchain.com"
explorer = "https://explorer-sepolia.inkonchain.com"
superchain_level = 0
standard_chain_candidate = true # This is a temporary field which causes most of the standard validation checks to run on this chain
superchain_time = 0 # Missing hardfork times are inherited from superchain.toml
batch_inbox_addr = "0x004De1914F4f17aC234f5A5Bc8a4072a231d44BF"
block_time = 1
seq_window_size = 3600
max_sequencer_drift = 600
data_availability_type = "eth-da"

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1729003296
  [genesis.l1]
    hash = "0x5fb818b4d3ba100eeb3347c508bca24752ee88f235120e108bd9ee5d1b2ae50b"
    number = 6880819
  [genesis.l2]
    hash = "0xe5fd5cf0be56af58ad5751b401410d6b7a09d830fa459789746a3d0dd1c79834"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x21e57C21530Bc33F12Ba96C9dDC135488365002F"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000000"
    scalar = "0x010000000000000000000000000000000000000000000000000c5fc500000558"
    gasLimit = 30000000

[addresses]
  SystemConfigOwner = "0xBeA2Bc852a160B8547273660E22F4F08C2fa9Bbb"
  ProxyAdminOwner = "0x1Eb2fFc903729a0F03966B917003800b145F56E2"
  Guardian = "0x7a50f00e8D05b95F98fE38d8BeE366a7324dCf7E"
  Challenger = "0xfd1D2e729aE8eEe2E146c033bf4400fE75284301"
  Proposer = "0xB15d792E30C5b7f67CBe5fe9Ba76685b537B4543"
  UnsafeBlockSigner = "0x43ec5732581d3FAE18AbB7CE34a796E111dBD1a0"
  BatchSubmitter = "0x21e57C21530Bc33F12Ba96C9dDC135488365002F"
  AddressManager = "0x3454F9df5E750F1383e58c1CB001401e7A4f3197"
  L1CrossDomainMessengerProxy = "0x9fE1d3523F5342535E6E7770ED09ed85Dbc1Acc2"
  L1ERC721BridgeProxy = "0xd1C901BBD7796546A7bA2492e0E199911fAE68c7"
  L1StandardBridgeProxy = "0x33f60714BbD74d62b66D79213C348614DE51901C"
  OptimismMintableERC20FactoryProxy = "0x686F782A749D1854f6Fa3F948450f4c65c6674f0"
  OptimismPortalProxy = "0x5c1d29C6c9C8b0800692acC95D700bcb4966A1d7"
  SystemConfigProxy = "0x05C993e60179f28bF649a2Bb5b00b5F4283bD525"
  ProxyAdmin = "0xd7dB319a49362b2328cf417a934300cCcB442C8d"
  SuperchainConfig = "0xC2Be75506d5724086DEB7245bd260Cc9753911Be"
  AnchorStateRegistryProxy = "0x89126a987717207d4E990ed2e8880fd170DceA1A"
  DelayedWETHProxy = "0x9fE1d3523F5342535E6E7770ED09ed85Dbc1Acc2"
  DisputeGameFactoryProxy = "0x860e626c700AF381133D9f4aF31412A2d1DB3D5d"
  PermissionedDisputeGame = "0xA8808360F7bc16Da81938e5C29400D18BeA651C4"
