name: Metal Sepolia
chain_id: 1740
public_rpc: https://testnet.rpc.metall2.com
sequencer_rpc: https://testnet.rpc.metall2.com
explorer: https://testnet.explorer.metall2.com

superchain_level: 2
superchain_time: nil # hardfork times are NOT yet inherited from superchain.yaml

batch_inbox_addr: "0x24567b64a86a4c966655fba6502a93dfb701e316"

genesis:
  l1:
    hash: "0x6a10927c70985f75898c48235b620acb2a48e9c777a40022f9dbad1b0c96a9c1"
    number: 5304030
  l2:
    hash: "0xd24cf8e46b189b0c128dab4e46168520e3a4cdd390b239e8cc1e5abd22a629ae"
    number: 0
  l2_time: 1708129620

delta_time: 1708385400   # Mon Feb 19 2024 23:30:00
ecotone_time: 1708534800
