name: Metal L2 Testnet
chain_id: 1740
public_rpc: https://testnet.rpc.metall2.com
sequencer_rpc: https://testnet.rpc.metall2.com
explorer: https://testnet.explorer.metall2.com

superchain_level: 1
standard_chain_candidate: true # This is a temporary field which causes most of the standard validation checks to run on this chain
superchain_time: null # Missing hardfork times are NOT yet inherited from superchain.yaml
contracts_version_tag: "op-contracts/v1.3.0" # Multi-Chain Prep (MCP) https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.3.0

batch_inbox_addr: "0x24567B64a86A4c966655fba6502a93dFb701E316"

genesis:
  l1:
    hash: "0x6a10927c70985f75898c48235b620acb2a48e9c777a40022f9dbad1b0c96a9c1"
    number: 5304030
  l2:
    hash: "0xd24cf8e46b189b0c128dab4e46168520e3a4cdd390b239e8cc1e5abd22a629ae"
    number: 0
  l2_time: 1708129620

canyon_time: 1708129622
delta_time: 1708385400 # Mon 19 Feb 2024 23:30:00 UTC
ecotone_time: 1708534800 # Wed 21 Feb 2024 17:00:00 UTC

block_time: 2
seq_window_size: 3600
