name = "Metal L2 Testnet"
public_rpc = "https://testnet.rpc.metall2.com"
sequencer_rpc = "https://testnet.rpc.metall2.com"
explorer = "https://testnet.explorer.metall2.com"
superchain_level = 1
governed_by_optimism = true
superchain_time = 1708534800
data_availability_type = "eth-da"
chain_id = 1740
batch_inbox_addr = "0x24567B64a86A4c966655fba6502a93dFb701E316"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 1708129622 # Sat 17 Feb 2024 00:27:02 UTC
  delta_time = 1708385400 # Mon 19 Feb 2024 23:30:00 UTC
  ecotone_time = 1708534800 # Wed 21 Feb 2024 17:00:00 UTC
  fjord_time = 1716998400 # Wed 29 May 2024 16:00:00 UTC
  granite_time = 1723478400 # Mon 12 Aug 2024 16:00:00 UTC
  holocene_time = 1732633200 # Tue 26 Nov 2024 15:00:00 UTC
  pectra_blob_schedule_time = 1742486400 # Thu 20 Mar 2025 16:00:00 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1708129620
  [genesis.l1]
    hash = "0x6a10927c70985f75898c48235b620acb2a48e9c777a40022f9dbad1b0c96a9c1"
    number = 5304030
  [genesis.l2]
    hash = "0xd24cf8e46b189b0c128dab4e46168520e3a4cdd390b239e8cc1e5abd22a629ae"
    number = 0
  [genesis.system_config]
    batcherAddress = "0xdb80Eca386AC72a55510e33CF9CF7533e75916eE"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x23BA22Dd7923F3a3f2495bB32a6f3c9b9CD1EC6C"
  ProxyAdminOwner = "0x1Eb2fFc903729a0F03966B917003800b145F56E2"
  Guardian = "0x7a50f00e8D05b95F98fE38d8BeE366a7324dCf7E"
  Challenger = "0x45eFFbD799Ab49122eeEAB75B78D9C56A187F9A7"
  BatchSubmitter = "0xdb80Eca386AC72a55510e33CF9CF7533e75916eE"

[addresses]
  AddressManager = "0x394f844B9A0FC876935d1b0b791D9e94Ad905e8b"
  L1CrossDomainMessengerProxy = "0x5D335Aa7d93102110879e3B54985c5F08146091E"
  L1ERC721BridgeProxy = "0x5d6cE6917dBeeacF010c96BfFdaBE89e33a30309"
  L1StandardBridgeProxy = "0x21530aAdF4DCFb9c477171400E40d4ef615868BE"
  L2OutputOracleProxy = "0x75a6B961c8da942Ee03CA641B09C322549f6FA98"
  OptimismMintableERC20FactoryProxy = "0x49Ff2C4be882298e8CA7DeCD195c207c42B45F66"
  OptimismPortalProxy = "0x01D4dfC994878682811b2980653D03E589f093cB"
  SystemConfigProxy = "0x5D63A8Dc2737cE771aa4a6510D063b6Ba2c4f6F2"
  ProxyAdmin = "0xF7Bc4b3a78C7Dd8bE9B69B3128EEB0D6776Ce18A"
