name = "Mode Testnet"
public_rpc = "https://sepolia.mode.network"
sequencer_rpc = "https://sepolia.mode.network"
explorer = "https://sepolia.explorer.mode.network"
superchain_level = 1
governed_by_optimism = true
superchain_time = 1703203200
data_availability_type = "eth-da"
chain_id = 919
batch_inbox_addr = "0xcDDaE6148dA1E003C230E4527f9baEdc8a204e7E"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 1703203200 # Fri 22 Dec 2023 00:00:00 UTC
  delta_time = 1703203200 # Fri 22 Dec 2023 00:00:00 UTC
  ecotone_time = 1708534800 # Wed 21 Feb 2024 17:00:00 UTC
  fjord_time = 1716998400 # Wed 29 May 2024 16:00:00 UTC
  granite_time = 1723478400 # Mon 12 Aug 2024 16:00:00 UTC
  holocene_time = 1732633200 # Tue 26 Nov 2024 15:00:00 UTC
  pectra_blob_schedule_time = 1742486400 # Thu 20 Mar 2025 16:00:00 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1687867932
  [genesis.l1]
    hash = "0x4370cafe528a1b8f2aaffc578094731daf69ff82fd9edc30d2d842d3763f3410"
    number = 3778382
  [genesis.l2]
    hash = "0x13c352562289a88ed33087a51b6b6c859a27709c8555c9def7cb9757c043acad"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x4e6BD53883107B063c502dDd49F9600Dc51b3DDc"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x23BA22Dd7923F3a3f2495bB32a6f3c9b9CD1EC6C"
  ProxyAdminOwner = "0x1Eb2fFc903729a0F03966B917003800b145F56E2"
  Guardian = "0x7a50f00e8D05b95F98fE38d8BeE366a7324dCf7E"
  Challenger = "0x45eFFbD799Ab49122eeEAB75B78D9C56A187F9A7"
  Proposer = "0xe9e08A478e3a773c1B5D59014A0FDb901e6d1d69"
  UnsafeBlockSigner = "0x93A14E6894eEB4FF6a373E1Ad4f498c3a207afe4"
  BatchSubmitter = "0x4e6BD53883107B063c502dDd49F9600Dc51b3DDc"

[addresses]
  AddressManager = "0x83D45725d6562d8CD717673D6bb4c67C07dC1905"
  L1CrossDomainMessengerProxy = "0xc19a60d9E8C27B9A43527c3283B4dd8eDC8bE15C"
  L1ERC721BridgeProxy = "0x015a8c2e0a5fEd579dbb05fd290e413Adc6FC24A"
  L1StandardBridgeProxy = "0xbC5C679879B2965296756CD959C3C739769995E2"
  L2OutputOracleProxy = "0x2634BD65ba27AB63811c74A63118ACb312701Bfa"
  OptimismMintableERC20FactoryProxy = "0x00F7ab8c72D32f55cFf15e8901C2F9f2BF29A3C0"
  OptimismPortalProxy = "0x320e1580effF37E008F1C92700d1eBa47c1B23fD"
  SystemConfigProxy = "0x15cd4f6e0CE3B4832B33cB9c6f6Fe6fc246754c2"
  ProxyAdmin = "0xE7413127F29E050Df65ac3FC9335F85bB10091AE"
