name: Mode Sepolia
chain_id: 919
public_rpc: https://sepolia.mode.network
sequencer_rpc: https://sepolia.mode.network
explorer: https://sepolia.explorer.mode.network

superchain_level: 1
standard_chain_candidate: true
superchain_time: 1703203200 # Fri 22 Dec 2023 00:00:00 UTC

batch_inbox_addr: "0xcDDaE6148dA1E003C230E4527f9baEdc8a204e7E"

genesis:
  l1:
    hash: "0x4370cafe528a1b8f2aaffc578094731daf69ff82fd9edc30d2d842d3763f3410"
    number: 3778382
  l2:
    hash: "0x13c352562289a88ed33087a51b6b6c859a27709c8555c9def7cb9757c043acad"
    number: 0
  l2_time: 1687867932

canyon_time: 1703203200  # Fri 22 Dec 2023 00:00:00 UTC
