name: OP Sepolia Testnet
short_name: opsep
chain_id: 11155420
public_rpc: "https://sepolia.optimism.io"
sequencer_rpc: "https://sepolia-sequencer.optimism.io"
explorer: "https://sepolia-optimistic.etherscan.io"

superchain_level: 2
superchain_time: 0 # Missing hardfork times are inherited from superchain.yaml
contracts_version_tag: "op-contracts/v1.4.0" # Fault Proofs https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.4.0

system_config_addr: "0x034edD2A225f7f429A63E0f1D2084B9E0A93b538"
batch_inbox_addr: "0xff00000000000000000000000000000011155420"

genesis:
  l1:
    hash: "0x48f520cf4ddaf34c8336e6e490632ea3cf1e5e93b0b2bc6e917557e31845371b"
    number: 4071408
  l2:
    hash: "0x102de6ffb001480cc9b8b548fd05c34cd4f46ae4aa91759393db90ea0409887d"
    number: 0
  l2_time: 1691802540 # Sat 12 Aug 2023 01:09:00 UTC
