name = "RACE Testnet"
chain_id = 6806
public_rpc = "https://racetestnet.io"
sequencer_rpc = "https://racetestnet.io"
explorer = "https://testnet.racescan.io/"
superchain_level = 0
batch_inbox_addr = "0xff00000000000000000000000000000000006806"
canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600
data_availability_type = "eth-da"

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1719646560
  [genesis.l1]
    hash = "0x28dd1dd74080560ef0b02f8f1ae31d1be75b01a70a5be6ef22e673cec538770f"
    number = 6210400
  [genesis.l2]
    hash = "0x994d67464c3368b8eb6f9770087399486b25d721a1868b95bb37de327b49ab89"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x584D61A30C7Ef1E8D547eE02099dADC487f49889"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000
 
[addresses]
  SystemConfigOwner = "0x84db348d3DD6519444556a116225f4dAa5aDB6B4"
  ProxyAdminOwner = "0xAc78E9B3Aa9373AE4bE2Ba5Bc9F716d7A746A65E"
  Guardian = "0x7a50f00e8D05b95F98fE38d8BeE366a7324dCf7E"
  Challenger = "0x777bf55BA06395C8b2c05DD43D0A40001d1B9982"
  Proposer = "0x5a145E3F466FD6cC095214C700359df7894BaD21"
  UnsafeBlockSigner = "0x89eA88ef4AC23f4C7Fdc611Fc9cD1c50DF702C2C"
  BatchSubmitter = "0x584D61A30C7Ef1E8D547eE02099dADC487f49889"
  AddressManager = "0x1B573Db1000eA419B6dE8eB482C6d394179Bd1A3"
  L1CrossDomainMessengerProxy = "0xdaeab17598938A4f27E50AC771249Ad7df12Ea7D"
  L1ERC721BridgeProxy = "0xBafb1a6e54e7750aF29489D65888d1c96Dfd66Df"
  L1StandardBridgeProxy = "0x289179e9d43A35D47239456251F9c2fdbf9fbeA2"
  L2OutputOracleProxy = "0xccac2B8FFc4f778242105F3a9E6B3Ae3F827fC6a"
  OptimismMintableERC20FactoryProxy = "0xbd023e7F08AE0274dCEd397D4B6630D697aC738A"
  OptimismPortalProxy = "0xF2891fc6819CDd6BD9221874619BB03A6277d72A"
  SystemConfigProxy = "0x07e7A3F25aA73dA15bc19B71FEF8f5511342a409"
  ProxyAdmin = "0x4a0E8415e3eB85E7393445FD8E588283b62216C8"
  SuperchainConfig = "0xC2Be75506d5724086DEB7245bd260Cc9753911Be"
  
  AnchorStateRegistryProxy = "0x7220581f363f28dA8C75c863942c54867C7C3A19"
  DelayedWETHProxy = "0xD5CA71Ffdb690416a4CF92c9DBae28AbAaBd5DD0"
  DisputeGameFactoryProxy = "0xbDC16b0E8C18C5E13Ed02221Aa85598AF486A88f"
  MIPS = "0x2b5687130B70dc89B8210BB90fB8958d0Cdcfd21"
  PermissionedDisputeGame = "0x63ACDF0B0d02A13D50ABe311eDC75cadaC39CAF9"
  PreimageOracle = "0x6164364fdF65A24e73446f63793159453e646434"
