name = "Sepolia"
protocol_versions_addr = "0x79ADD5713B383DAa0a138d3C4780C7A1804a8090"
superchain_config_addr = "0xC2Be75506d5724086DEB7245bd260Cc9753911Be"
<<<<<<< HEAD
op_contracts_manager_proxy_addr = "0xF564eEA7960EA244bfEbCBbB17858748606147bf"
=======
op_contracts_manager_proxy_addr = "0xf564eea7960ea244bfebcbbb17858748606147bf"
>>>>>>> cc8e7ba (fix: adding to superchain.toml files.)

canyon_time =  1699981200 # Tue 14 Nov 2023 17:00:00 UTC
delta_time =   1703203200 # Fri 22 Dec 2023 00:00:00 UTC
ecotone_time = 1708534800 # Wed 21 Feb 2024 17:00:00 UTC
fjord_time =   1716998400 # Wed 29 May 2024 16:00:00 UTC
granite_time = 1723478400 # Mon Aug 12 16:00:00 UTC

[l1]
  chain_id = 11155111
  public_rpc = "https://ethereum-sepolia-rpc.publicnode.com"
  explorer = "https://sepolia.etherscan.io"
