name: Zora Sepolia
chain_id: 999999999
public_rpc: "https://sepolia.rpc.zora.energy"
sequencer_rpc: "https://sepolia.rpc.zora.energy"
explorer: "https://sepolia.explorer.zora.energy"

system_config_addr: "0xB54c7BFC223058773CF9b739cC5bd4095184Fb08"
batch_inbox_addr: "0xCd734290E4bd0200dAC631c7D4b9E8a33234e91f"

genesis:
  l1:
    hash: "0xf782446a2487d900addb5d466a8597c7c543b59fa9aaa154d413830238f8798a"
    number: 4548041
  l2:
    hash: "0x8b17d2d52564a5a90079d9c860e1386272579e87b17ea27a3868513f53facd74"
    number: 0
  l2_time: 1698080004
