configType = "standard"
l1ChainID = 0
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "tag://op-contracts/v3.0.0"
l2ContractsLocator = "tag://op-contracts/v3.0.0"

[superchainRoles]
  proxyAdminOwner = "0x0000000000000000000000000000000000000000"
  protocolVersionsOwner = "0x0000000000000000000000000000000000000000"
  guardian = "0x0000000000000000000000000000000000000000"

[[chains]]
  id = "0x00000000000000000000000000000000000000000000000000000000000004d2"
  baseFeeVaultRecipient = "0x0000000000000000000000000000000000000000"
  l1FeeVaultRecipient = "0x0000000000000000000000000000000000000000"
  sequencerFeeVaultRecipient = "0x0000000000000000000000000000000000000000"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  operatorFeeConstant = 0
  operatorFeeScalar = 0
  [chains.roles]
    l1ProxyAdminOwner = "0x0000000000000000000000000000000000000000"
    l2ProxyAdminOwner = "0x0000000000000000000000000000000000000000"
    systemConfigOwner = "0x0000000000000000000000000000000000000000"
    unsafeBlockSigner = "0x0000000000000000000000000000000000000000"
    batcher = "0x0000000000000000000000000000000000000000"
    proposer = "0x0000000000000000000000000000000000000000"
    challenger = "0x0000000000000000000000000000000000000000"
