configType = "standard"
l1ChainID = 0
opcmAddress = "0x0000000000000000000000000000000000000000"
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "tag://op-contracts/v4.0.0-rc.7"
l2ContractsLocator = "tag://op-contracts/v4.0.0-rc.7"

[superchainRoles]
  SuperchainProxyAdminOwner = "0x0000000000000000000000000000000000000000"
  ProtocolVersionsOwner = "0x0000000000000000000000000000000000000000"
  SuperchainGuardian = "0x0000000000000000000000000000000000000000"

[[chains]]
  id = "0x00000000000000000000000000000000000000000000000000000000000004d2"
  baseFeeVaultRecipient = "0x0000000000000000000000000000000000000000"
  l1FeeVaultRecipient = "0x0000000000000000000000000000000000000000"
  sequencerFeeVaultRecipient = "0x0000000000000000000000000000000000000000"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  gasLimit = 60000000
  operatorFeeConstant = 0
  operatorFeeScalar = 0
  [chains.roles]
    l1ProxyAdminOwner = "0x0000000000000000000000000000000000000000"
    l2ProxyAdminOwner = "0x0000000000000000000000000000000000000000"
    systemConfigOwner = "0x0000000000000000000000000000000000000000"
    unsafeBlockSigner = "0x0000000000000000000000000000000000000000"
    batcher = "0x0000000000000000000000000000000000000000"
    proposer = "0x0000000000000000000000000000000000000000"
    challenger = "0x0000000000000000000000000000000000000000"
