name = "Base"
public_rpc = "https://mainnet.base.org"
sequencer_rpc = "https://mainnet-sequencer.base.org"
explorer = "https://explorer.base.org"
superchain_level = 1
governed_by_optimism = false
superchain_time = 0
data_availability_type = "eth-da"
chain_id = 8453
batch_inbox_addr = "0xFf00000000000000000000000000000000008453"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 1704992401 # Thu 11 Jan 2024 17:00:01 UTC
  delta_time = 1708560000 # Thu 22 Feb 2024 00:00:00 UTC
  ecotone_time = 1710374401 # Thu 14 Mar 2024 00:00:01 UTC
  fjord_time = 1720627201 # Wed 10 Jul 2024 16:00:01 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1686789347
  [genesis.l1]
    hash = "0x5c13d307623a926cd31415036c8b7fa14572f9dac64528e857a470511fc30771"
    number = 17481768
  [genesis.l2]
    hash = "0xf712aa9241cc24369b143cf6dce85f0902a9731e70d66818a3a5845b296c73dd"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x5050F69a9786F081509234F1a7F4684b5E5b76C9"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x14536667Cd30e52C0b458BaACcB9faDA7046E056"
  ProxyAdminOwner = "0x7bB41C3008B3f03FE483B28b8DB90e19Cf07595c"
  Guardian = "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2"
  Challenger = "0x6F8C5bA3F59ea3E76300E3BEcDC231D656017824"
  Proposer = "0x642229f238fb9dE03374Be34B0eD8D9De80752c5"
  UnsafeBlockSigner = "0xAf6E19BE0F9cE7f8afd49a1824851023A8249e8a"
  BatchSubmitter = "0x5050F69a9786F081509234F1a7F4684b5E5b76C9"

[addresses]
  AddressManager = "0x8EfB6B5c4767B09Dc9AA6Af4eAA89F749522BaE2"
  L1CrossDomainMessengerProxy = "0x866E82a600A1414e583f7F13623F1aC5d58b0Afa"
  L1ERC721BridgeProxy = "0x608d94945A64503E642E6370Ec598e519a2C1E53"
  L1StandardBridgeProxy = "0x3154Cf16ccdb4C6d922629664174b904d80F2C35"
  L2OutputOracleProxy = "0x56315b90c40730925ec5485cf004d835058518A0"
  OptimismMintableERC20FactoryProxy = "0x05cc379EBD9B30BbA19C6fA282AB29218EC61D84"
  OptimismPortalProxy = "0x49048044D57e1C92A77f79988d21Fa8fAF74E97e"
  SystemConfigProxy = "0x73a79Fab69143498Ed3712e519A88a918e1f4072"
  ProxyAdmin = "0x0475cBCAebd9CE8AfA5025828d5b98DFb67E059E"
  AnchorStateRegistryProxy = "0xdB9091e48B1C42992A1213e6916184f9eBDbfEDf"
  DelayedWETHProxy = "0xa2f2aC6F5aF72e494A227d79Db20473Cf7A1FFE8"
  DisputeGameFactoryProxy = "0x43edB88C4B80fDD2AdFF2412A7BebF9dF42cB40e"
  FaultDisputeGame = "0xCd3c0194db74C23807D4B90A5181e1B28cF7007C"
  MIPS = "0x16e83cE5Ce29BF90AD9Da06D2fE6a15d5f344ce4"
  PermissionedDisputeGame = "0x19009dEBF8954B610f207D5925EEDe827805986e"
  PreimageOracle = "0x9c065e11870B891D214Bc2Da7EF1f9DDFA1BE277"
