name = "Celo"
public_rpc = "https://forno.celo.org"
sequencer_rpc = "https://cel2-sequencer.celo.org/"
explorer = "https://celoscan.io/"
superchain_level = 0
governed_by_optimism = false
data_availability_type = "alt-da"
chain_id = 42220
batch_inbox_addr = "0xff00000000000000000000000000000000042220"
block_time = 1
seq_window_size = 7200
max_sequencer_drift = 2892
gas_paying_token = "0x057898f3C43F129a17517B9056D23851F124b19f"

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  granite_time = 0 # Thu 1 Jan 1970 00:00:00 UTC

[optimism]
  eip1559_elasticity = 5
  eip1559_denominator = 400
  eip1559_denominator_canyon = 400

[genesis]
  l2_time = 1742957258
  [genesis.l1]
    hash = "0xe499ec12e12fc2c94e6714a94f2640dbc748ff6c26fd3f420b25264a3d90066f"
    number = 22128103
  [genesis.l2]
    hash = "0x7586014e20c69b3fa7c9070baf1a7edd95833db57853126f32593b455da2e5c5"
    number = 31056500
  [genesis.system_config]
    batcherAddress = "0x0cd08c7f7a96aa9635f761b49216b9ea74c5ca60"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000000"
    scalar = "0x0100000000000000000000000000000000000000000000000000000000000000"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x4092A77bAF58fef0309452cEaCb09221e556E112"
  ProxyAdminOwner = "0x4092A77bAF58fef0309452cEaCb09221e556E112"
  Guardian = "0x6E226fa22e5F19363d231D3FA048aaBa73CC1f47"
  Challenger = "0x6b145Ebf66602Ec524b196426B46631259689583"
  Proposer = "0x1204884E697efD929729B9A717Ea14496298A689"
  UnsafeBlockSigner = "0xA6F1c6c24De8b112dd3867dB907d187d490e6ddF"
  BatchSubmitter = "0x0cd08c7f7a96aa9635f761b49216b9ea74c5ca60"

[addresses]
  AddressManager = "0x55093104b76FAA602F9d6c35A5FFF576bE78d753"
  L1CrossDomainMessengerProxy = "0x1AC1181fc4e4F877963680587AEAa2C90D7EbB95"
  L1ERC721BridgeProxy = "0x3C519816C5BdC0a0199147594F83feD4F5847f13"
  L1StandardBridgeProxy = "0x9C4955b92F34148dbcfDCD82e9c9eCe5CF2badfe"
  L2OutputOracleProxy = "0x7617b249AEb1F06c90BDF9C4F6C903C09a6a4220"
  OptimismMintableERC20FactoryProxy = "0x6f0E4f1EB98A52EfaCF7BE11d48B9d9d6510A906"
  OptimismPortalProxy = "0xc5c5D157928BDBD2ACf6d0777626b6C75a9EAEDC"
  SystemConfigProxy = "0x89E31965D844a309231B1f17759Ccaf1b7c09861"
  ProxyAdmin = "0x783A434532Ee94667979213af1711505E8bFE374"
  SuperchainConfig = "0x95703e0982140D16f8ebA6d158FccEde42f04a4C"
  AnchorStateRegistryProxy = "0xa24Bf5Bc02997f63da4e2C7F802067e05a102504"
  DelayedWETHProxy = "0xa316D42E8Fd98D2Ec364b8bF853d2623E768f95a"
  DisputeGameFactoryProxy = "0xFbAC162162f4009Bb007C6DeBC36B1dAC10aF683"
  MIPS = "0x8A12E1754f729C0856E2E32D4821577f0B245bfA"
  PreimageOracle = "0xfaB0F466955D87e596Ca87E20c505bB6470D0DC4"
