name = "Cyber Mainnet"
public_rpc = "https://rpc.cyber.co"
sequencer_rpc = "https://cyber.alt.technology/"
explorer = "https://cyberscan.co/"
superchain_level = 0
governed_by_optimism = false
data_availability_type = "alt-da"
chain_id = 7560
batch_inbox_addr = "0xfF00000000000000000000000000000000001d88"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 1767754800 # Wed 7 Jan 2026 03:00:00 UTC
  granite_time = 1767841200 # Thu 8 Jan 2026 03:00:00 UTC
  holocene_time = 1767927600 # Fri 9 Jan 2026 03:00:00 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[alt_da]
  da_challenge_contract_address = "0x10E34EfE14E4D270C0f77Bf1aF01b6C832161B49"
  da_challenge_window = 3600
  da_resolve_window = 3600
  da_commitment_type = "KeccakCommitment"

[genesis]
  l2_time = 1713428567
  [genesis.l1]
    hash = "0x8fa2a34b37420b863aa33da7661a8929af8bd7a436b9e612c727eb5e63da3879"
    number = 19681125
  [genesis.l2]
    hash = "0x0bbf36c47db3b42b40b2e6cadc183612337d1ac8602eb9e57071ae0043e70fc7"
    number = 0
  [genesis.system_config]
    batcherAddress = "0xf0748C52EDC23135d9845CDFB91279Cf61ee14b4"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000b4"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  ProxyAdminOwner = "0xc2259E7Fb719411f97aBdCdf449f6Ba3B9D75398"

[addresses]
  L1StandardBridgeProxy = "0x12a580c05466eefb2c467C6b115844cDaF55B255"
  OptimismPortalProxy = "0x1d59bc9fcE6B8E2B1bf86D4777289FFd83D24C99"
  SystemConfigProxy = "0x5D1F4bbaF6D484fA9D5D9705f92dE6063bff6055"
  DisputeGameFactoryProxy = "0xbF4676f21a7889E0Fd61BcDc9b98E60b01C1B36F"
