name = "Ink"
public_rpc = "https://rpc-gel.inkonchain.com"
sequencer_rpc = "https://rpc-gel.inkonchain.com"
explorer = "https://explorer.inkonchain.com"
superchain_level = 1
governed_by_optimism = true
superchain_time = 1742396400
data_availability_type = "eth-da"
chain_id = 57073
batch_inbox_addr = "0x005969bf0EcbF6eDB6C47E5e94693b1C3651Be97"
block_time = 1
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  granite_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  holocene_time = 1742396400 # Wed 19 Mar 2025 15:00:00 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 250
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1733498411
  [genesis.l1]
    hash = "0x39e4e0c0c94f8076134b441a9dc18d10b595fd9777edeb763bb9f9bd8f922fd9"
    number = 21344310
  [genesis.l2]
    hash = "0x23a2658170ba70d014ba0d0d2709f8fbfe2fa660cd868c5f282f991eecbe38ee"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x500d7Ea63CF2E501dadaA5feeC1FC19FE2Aa72Ac"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000000"
    scalar = "0x010000000000000000000000000000000000000000000000000c5fc500000558"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0xBeA2Bc852a160B8547273660E22F4F08C2fa9Bbb"
  ProxyAdminOwner = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"
  Guardian = "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2"
  Challenger = "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A"
  Proposer = "0x65436ddCbc026F34118954F229f7F132b696b3B4"
  UnsafeBlockSigner = "0x7D056B99AA2021864c42E25B4F8cE3BdEAc9463C"
  BatchSubmitter = "0x500d7Ea63CF2E501dadaA5feeC1FC19FE2Aa72Ac"

[addresses]
  AddressManager = "0x9b7C9BbD6d540A8A4dEDd935819fC4408Ba71153"
  L1CrossDomainMessengerProxy = "0x69d3Cf86B2Bf1a9e99875B7e2D9B6a84426c171f"
  L1ERC721BridgeProxy = "0x661235a238B11191211fa95D4Dd9E423d521E0Be"
  L1StandardBridgeProxy = "0x88FF1e5b602916615391F55854588EFcBB7663f0"
  OptimismMintableERC20FactoryProxy = "0xA8B389A82e088b164cD03230e900980CcED34d29"
  OptimismPortalProxy = "0x5d66C1782664115999C47c9fA5cd031f495D3e4F"
  SystemConfigProxy = "0x62C0a111929fA32ceC2F76aDba54C16aFb6E8364"
  ProxyAdmin = "0xd56045E68956FCe2576E680c95a4750cf8241f79"
  SuperchainConfig = "0x95703e0982140D16f8ebA6d158FccEde42f04a4C"
  AnchorStateRegistryProxy = "0xde744491BcF6b2DD2F32146364Ea1487D75E2509"
  DelayedWETHProxy = "0x3Beaca17eaE5643FB1479AA5f4B1fF75cc4b9B50"
  DisputeGameFactoryProxy = "0x10d7B35078d3baabB96Dd45a9143B94be65b12CD"
  FaultDisputeGame = "0x6A8eFcba5642EB15D743CBB29545BdC44D5Ad8cD"
  MIPS = "0x16e83cE5Ce29BF90AD9Da06D2fE6a15d5f344ce4"
  PermissionedDisputeGame = "0x0A780bE3eB21117b1bBCD74cf5D7624A3a482963"
  PreimageOracle = "0x9c065e11870B891D214Bc2Da7EF1f9DDFA1BE277"
