name = "Metal L2"
public_rpc = "https://rpc.metall2.com"
sequencer_rpc = "https://rpc.metall2.com"
explorer = "https://explorer.metall2.com"
superchain_level = 1
governed_by_optimism = true
superchain_time = 0
data_availability_type = "eth-da"
chain_id = 1750
batch_inbox_addr = "0xc83f7D9F2D4A76E81145849381ABA02602373723"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 1720627201 # Wed 10 Jul 2024 16:00:01 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1711563515
  [genesis.l1]
    hash = "0x2493565ce8472656b7c22377c8d4d8ef5d17f78392c799ca5f2429b01e2c159c"
    number = 19527340
  [genesis.l2]
    hash = "0xd31c12ffff2d563897ad9a041c0d26790d635911bdbbfa589347fa955f75281e"
    number = 0
  [genesis.system_config]
    batcherAddress = "0xC94C243f8fb37223F3EB2f7961F7072602A51B8B"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x4a4962275DF8C60a80d3a25faEc5AA7De116A746"
  ProxyAdminOwner = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"
  Guardian = "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2"
  Challenger = "0x4a4962275DF8C60a80d3a25faEc5AA7De116A746"
  Proposer = "0xC8187d40AD440328104A52BBed2D8Efc5ab1F1F6"
  UnsafeBlockSigner = "0x4a65F5da5e80DEFfEA844eAa15CE130e80605dc5"
  BatchSubmitter = "0xC94C243f8fb37223F3EB2f7961F7072602A51B8B"

[addresses]
  AddressManager = "0xd4b1EC0DEc3C7F12abD3ec27B7514880ae1C3a37"
  L1CrossDomainMessengerProxy = "0x0a47A44f1B2bb753474f8c830322554A96C9934D"
  L1ERC721BridgeProxy = "0x50D700e97967F9115e3f999bDB263d69F6704680"
  L1StandardBridgeProxy = "0x6d0f65D59b55B0FEC5d2d15365154DcADC140BF3"
  L2OutputOracleProxy = "0x3B1F7aDa0Fcc26B13515af752Dd07fB1CAc11426"
  OptimismMintableERC20FactoryProxy = "0x1aaab4E20d2e4Bb992b5BCA2125e8bd3588c8730"
  OptimismPortalProxy = "0x3F37aBdE2C6b5B2ed6F8045787Df1ED1E3753956"
  SystemConfigProxy = "0x7BD909970B0EEdcF078De6Aeff23ce571663b8aA"
  ProxyAdmin = "0x37Ff0ae34dadA1A95A4251d10ef7Caa868c7AC99"
