name = "Mode"
public_rpc = "https://mainnet.mode.network"
sequencer_rpc = "https://mainnet-sequencer.mode.network"
explorer = "https://explorer.mode.network"
superchain_level = 1
governed_by_optimism = true
superchain_time = 0
data_availability_type = "eth-da"
chain_id = 34443
batch_inbox_addr = "0x24E59d9d3Bd73ccC28Dc54062AF7EF7bFF58Bd67"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 1704992401 # Thu 11 Jan 2024 17:00:01 UTC
  delta_time = 1708560000 # Thu 22 Feb 2024 00:00:00 UTC
  ecotone_time = 1710374401 # Thu 14 Mar 2024 00:00:01 UTC
  fjord_time = 1720627201 # Wed 10 Jul 2024 16:00:01 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1700167583
  [genesis.l1]
    hash = "0xf9b1b22a7ef9d13f063ea467bcb70fb6e9f29698ecb7366a2cdf5af2165cacee"
    number = 18586927
  [genesis.l2]
    hash = "0xb0f682e12fc555fd5ce8fce51a59a67d66a5b46be28611a168260a549dac8a9b"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x99199a22125034c808ff20f377d91187E8050F2E"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x4a4962275DF8C60a80d3a25faEc5AA7De116A746"
  ProxyAdminOwner = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"
  Guardian = "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2"
  Challenger = "0x309Fe2536d01867018D120b40e4676723C53A14C"
  Proposer = "0x674F64D64Ddc198db83cd9047dF54BF89cCD0ddB"
  UnsafeBlockSigner = "0xa7fA9CA4ac88686A542C0f830d7378eAB4A0278F"
  BatchSubmitter = "0x99199a22125034c808ff20f377d91187E8050F2E"

[addresses]
  AddressManager = "0x50eF494573f28Cad6B64C31b7a00Cdaa48306e15"
  L1CrossDomainMessengerProxy = "0x95bDCA6c8EdEB69C98Bd5bd17660BaCef1298A6f"
  L1ERC721BridgeProxy = "0x2901dA832a4D0297FF0691100A8E496626cc626D"
  L1StandardBridgeProxy = "0x735aDBbE72226BD52e818E7181953f42E3b0FF21"
  L2OutputOracleProxy = "0x4317ba146D4933D889518a3e5E11Fe7a53199b04"
  OptimismMintableERC20FactoryProxy = "0x69216395A62dFb243C05EF4F1C27AF8655096a95"
  OptimismPortalProxy = "0x8B34b14c7c7123459Cf3076b8Cb929BE097d0C07"
  SystemConfigProxy = "0x5e6432F18Bc5d497B1Ab2288a025Fbf9D69E2221"
  ProxyAdmin = "0x470d87b1dae09a454A43D1fD772A561a03276aB7"
