name = "Polynomial"
public_rpc = "https://rpc.polynomial.fi"
sequencer_rpc = "https://rpc.polynomial.fi"
explorer = "https://polynomialscan.io"
superchain_level = 1
governed_by_optimism = false
superchain_time = 0
data_availability_type = "eth-da"
chain_id = 8008
batch_inbox_addr = "0x0bd57e83B5E0f9eCD84d559bB58e1EcFEEdD2565"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 1720627201 # Wed 10 Jul 2024 16:00:01 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC
  isthmus_time = 1746806401 # Fri 9 May 2025 16:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1718038175
  [genesis.l1]
    hash = "0xc6d18992ff6e4c9e4798d34a7b97423a7ec276e9f2bbecfd4bb69ccdd49f516a"
    number = 20062729
  [genesis.l2]
    hash = "0x1b5e76ad2f290fb6fa2c60755d8c52942dbefedab76d01091e24080d5c129fd0"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x67a44CE38627F46F20b1293960559eD85Dd194F1"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  ProxyAdminOwner = "0x4a4962275DF8C60a80d3a25faEc5AA7De116A746"

[addresses]
  L1StandardBridgeProxy = "0x3Be64BF2b9C2dE637067C7AAb6baE5EDf9fEBA55"
  OptimismPortalProxy = "0x034cbb620d1e0e4C2E29845229bEAc57083b04eC"
  SystemConfigProxy = "0x58b51fb9FeeD00DD846f91D265Eba3cdd855A413"
  DisputeGameFactoryProxy = "0xe9394679d0f0676E4a2dE99F8ed6B4aCb16c5f0f"
