name: Mainnet
l1:
  chain_id: 1
  public_rpc: https://mainnet.infura.io/v3/a0e6212bdaa547878a300083366b9720
  explorer: https://etherscan.io

protocol_versions_addr: "0x8062AbC286f5e7D9428a0Ccb9AbD71e50d93b935"
superchain_config_addr: "0x95703e0982140D16f8ebA6d158FccEde42f04a4C"

canyon_time:  1704992401 # Thu 11 Jan 2024 17:00:01 UTC
delta_time:   1708560000 # Thu 22 Feb 2024 00:00:00 UTC
ecotone_time: 1710374401 # Thu 14 Mar 2024 00:00:01 UTC
fjord_time:   1720627201 # Wed Jul 10 16:00:01 UTC 2024
