name = "Swellchain"
public_rpc = "https://swell-mainnet.alt.technology"
sequencer_rpc = "https://swell-mainnet.alt.technology"
explorer = "https://explorer.swellnetwork.io"
superchain_level = 1
governed_by_optimism = true
superchain_time = 1764691201
data_availability_type = "eth-da"
chain_id = 1923
batch_inbox_addr = "0x005dE5857e38dFD703a1725c0900E9C6f24cbdE0"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  granite_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  holocene_time = 1752732000 # Thu 17 Jul 2025 06:00:00 UTC
  isthmus_time = 1764648001 # Tue 2 Dec 2025 04:00:01 UTC
  jovian_time = 1764691201 # Tue 2 Dec 2025 16:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1732696703
  [genesis.l1]
    hash = "0xd904f8475cc7b74a9ef4749d0ee9aeca3b233aa3dc143667e8a20ffe43789a26"
    number = 21277945
  [genesis.l2]
    hash = "0x92379973a1576876b7337a9ce89e2a7a9cb99887f55e6045ed2069d5d98d9319"
    number = 0
  [genesis.system_config]
    batcherAddress = "0xf854cd5B26bfd73d51236c0122798907Ed65B1f2"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000000"
    scalar = "0x010000000000000000000000000000000000000000000000000c5fc500000558"
    gasLimit = 60000000

[roles]
  ProxyAdminOwner = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"

[addresses]
  L1StandardBridgeProxy = "0x7aA4960908B13D104bf056B23E2C76B43c5AACc8"
  OptimismPortalProxy = "0x758E0EE66102816F5C3Ec9ECc1188860fbb87812"
  SystemConfigProxy = "0xD3d4c6B703978a5d24FecF3a70a51127667Ff1A4"
  DisputeGameFactoryProxy = "0x87690676786cDc8cCA75A472e483AF7C8F2f0F57"
