name = "Binary Mainnet"
public_rpc = "https://rpc.zero.thebinaryholdings.com"
sequencer_rpc = "https://sequencer.bnry.mainnet.zeeve.net"
explorer = "https://explorer.thebinaryholdings.com"
superchain_level = 0
governed_by_optimism = false
superchain_time = 1726070401
data_availability_type = "eth-da"
chain_id = 624
batch_inbox_addr = "0xFF00000000000000000000000000000000000624"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600
gas_paying_token = "0x04E9D7e336f79Cdab911b06133D3Ca2Cd0721ce3"

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 1725536344 # Thu 5 Sep 2024 11:39:04 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC
  isthmus_time = 1746806401 # Fri 9 May 2025 16:00:01 UTC
  jovian_time = 1764691201 # Tue 2 Dec 2025 16:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1719397463
  [genesis.l1]
    hash = "0xdcc5838ee3dd0af995c87bec9614a09f08dd8979014876b42fd7e3ae044dd8c4"
    number = 20175246
  [genesis.l2]
    hash = "0xe222b4b07ee9c885d13ee341823c92aa449f9769ac68fb5f1e1d4e602a990a4a"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x7f9D9c1BCE1062E1077845eA39a0303429600a06"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000000"
    scalar = "0x010000000000000000000000000000000000000000000000000c5fc500000558"
    gasLimit = 30000000

[roles]
  ProxyAdminOwner = "0x48EC051349dDc7E8baBafCBfe27696ECF2A8a8B3"

[addresses]
  L1StandardBridgeProxy = "0xD1B30378CBF968E5525e8835219A5726A1e71D10"
  OptimismPortalProxy = "0x5ff88fcF8e9947f45F4cAf8FFd5231B5DdF05e0A"
  SystemConfigProxy = "0x7aC7e5989EaC278B7BbfeF560871a2026baD472c"
  DisputeGameFactoryProxy = "0x0D7e0590c58e4aC9B14B3eD6163CF55223931699"
