name = "Unichain"
public_rpc = "https://mainnet.unichain.org"
sequencer_rpc = "https://mainnet-sequencer.unichain.org"
explorer = "https://explorer.unichain.org"
superchain_level = 1
governed_by_optimism = true
superchain_time = 0
data_availability_type = "eth-da"
chain_id = 130
batch_inbox_addr = "0xFf00000000000000000000000000000000000130"
block_time = 1
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  delta_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  ecotone_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  fjord_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  granite_time = 0 # Thu 1 Jan 1970 00:00:00 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC
  isthmus_time = 1746806401 # Fri 9 May 2025 16:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1730748359
  [genesis.l1]
    hash = "0x8c799ed21bd97471f76ba48ea54b30f8169c7e4e4a22acfba06951b571e0f4b6"
    number = 21116363
  [genesis.l2]
    hash = "0x3425162ddf41a0a1f0106d67b71828c9a9577e6ddeb94e4f33d2cde1fdc3befe"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x2F60A5184c63ca94f82a27100643DbAbe4F3f7Fd"
    overhead = "0x0000000000000000000000000000000000000000000000000000000000000000"
    scalar = "0x010000000000000000000000000000000000000000000000000dbba0000007d0"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0x9245d5D10AA8a842B31530De71EA86c0760Ca1b1"
  ProxyAdminOwner = "0x6d5B183F538ABB8572F5cD17109c617b994D5833"
  Guardian = "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2"
  Challenger = "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A"
  Proposer = "0xD5F0E2912C70771C589CD8bB087EDE0Dab4AFA9A"
  UnsafeBlockSigner = "0x833C6f278474A78658af91aE8edC926FE33a230e"
  BatchSubmitter = "0x2F60A5184c63ca94f82a27100643DbAbe4F3f7Fd"

[addresses]
  AddressManager = "0x8098F676033A377b9Defe302e9fE6877cD63D575"
  L1CrossDomainMessengerProxy = "0x9A3D64E386C18Cb1d6d5179a9596A4B5736e98A6"
  L1ERC721BridgeProxy = "0xD04D0D87E0bd4D2E50286760a3EF323FeA6849Cf"
  L1StandardBridgeProxy = "0x81014F44b0a345033bB2b3B21C7a1A308B35fEeA"
  OptimismMintableERC20FactoryProxy = "0xA2B597EaeAcb6F627e088cbEaD319e934ED5edad"
  OptimismPortalProxy = "0x0bd48f6B86a26D3a217d0Fa6FfE2B491B956A7a2"
  SystemConfigProxy = "0xc407398d063f942feBbcC6F80a156b47F3f1BDA6"
  ProxyAdmin = "0x3B73Fa8d82f511A3caE17B5a26E4E1a2d5E2f2A4"
  SuperchainConfig = "0x95703e0982140D16f8ebA6d158FccEde42f04a4C"
  AnchorStateRegistryProxy = "0x27Cf508E4E3Aa8d30b3226aC3b5Ea0e8bcaCAFF9"
  DelayedWETHProxy = "0xBcEA39a1F75D7AC8004982efBA85F92A693386CB"
  DisputeGameFactoryProxy = "0x2F12d621a16e2d3285929C9996f478508951dFe4"
  FaultDisputeGame = "0x4F0f6B7877A174A4fd41DF80dB80DeF8883bc772"
  MIPS = "0xA1B54D89e305bcd322Ba0C9C094093173C0d6b3a"
  PermissionedDisputeGame = "0xC56EF9c3F3e9fD6713055b4577AC4AF8303E63e1"
  PreimageOracle = "0x1fb8cdFc6831fc866Ed9C51aF8817Da5c287aDD3"
