name = "Zora"
public_rpc = "https://rpc.zora.energy"
sequencer_rpc = "https://rpc.zora.energy"
explorer = "https://explorer.zora.energy"
superchain_level = 1
governed_by_optimism = true
superchain_time = 0
data_availability_type = "eth-da"
chain_id = 7777777
batch_inbox_addr = "0x6F54Ca6F6EdE96662024Ffd61BFd18f3f4e34DFf"
block_time = 2
seq_window_size = 3600
max_sequencer_drift = 600

[hardforks]
  canyon_time = 1704992401 # Thu 11 Jan 2024 17:00:01 UTC
  delta_time = 1708560000 # Thu 22 Feb 2024 00:00:00 UTC
  ecotone_time = 1710374401 # Thu 14 Mar 2024 00:00:01 UTC
  fjord_time = 1720627201 # Wed 10 Jul 2024 16:00:01 UTC
  granite_time = 1726070401 # Wed 11 Sep 2024 16:00:01 UTC
  holocene_time = 1736445601 # Thu 9 Jan 2025 18:00:01 UTC

[optimism]
  eip1559_elasticity = 6
  eip1559_denominator = 50
  eip1559_denominator_canyon = 250

[genesis]
  l2_time = 1686693839
  [genesis.l1]
    hash = "0xbdbd2847f7aa5f7cd1bd4c9f904057f4ba0b498c7e380199c01d240e3a41a84f"
    number = 17473923
  [genesis.l2]
    hash = "0x47555a45a1af8d4728ca337a1e48375a83919b1ea16591e070a07388b7364e29"
    number = 0
  [genesis.system_config]
    batcherAddress = "0x625726c858dBF78c0125436C943Bf4b4bE9d9033"
    overhead = "0x00000000000000000000000000000000000000000000000000000000000000bc"
    scalar = "0x00000000000000000000000000000000000000000000000000000000000a6fe0"
    gasLimit = 30000000

[roles]
  SystemConfigOwner = "0xC72aE5c7cc9a332699305E29F68Be66c73b60542"
  ProxyAdminOwner = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"
  Guardian = "0x09f7150D8c019BeF34450d6920f6B3608ceFdAf2"
  Challenger = "0xcA4571b1ecBeC86Ea2E660d242c1c29FcB55Dc72"
  Proposer = "0x48247032092e7b0ecf5dEF611ad89eaf3fC888Dd"
  UnsafeBlockSigner = "0x3Dc8Dfd0709C835cAd15a6A27e089FF4cF4C9228"
  BatchSubmitter = "0x625726c858dBF78c0125436C943Bf4b4bE9d9033"

[addresses]
  AddressManager = "0xEF8115F2733fb2033a7c756402Fc1deaa56550Ef"
  L1CrossDomainMessengerProxy = "0xdC40a14d9abd6F410226f1E6de71aE03441ca506"
  L1ERC721BridgeProxy = "0x83A4521A3573Ca87f3a971B169C5A0E1d34481c3"
  L1StandardBridgeProxy = "0x3e2Ea9B92B7E48A52296fD261dc26fd995284631"
  L2OutputOracleProxy = "0x9E6204F750cD866b299594e2aC9eA824E2e5f95c"
  OptimismMintableERC20FactoryProxy = "0xc52BC7344e24e39dF1bf026fe05C4e6E23CfBcFf"
  OptimismPortalProxy = "0x1a0ad011913A150f69f6A19DF447A0CfD9551054"
  SystemConfigProxy = "0xA3cAB0126d5F504B071b81a3e8A2BBBF17930d86"
  ProxyAdmin = "0xD4ef175B9e72cAEe9f1fe7660a6Ec19009903b49"
